clints/urls.py
from django.urls import path
from . import views
app_name='clints'

urlpatterns = [
    path('', views.index,name='intex'),
]

homepage/urls.py
from django.urls import path,include
from . import views
app_name='homepg'

urlpatterns = [
    path('', views.home,name='home'),
    path('movies', views.movies,name='movie'),
    path('tvshows', views.tvshows,name='shows'),
]

netflix/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('clints.urls')),
    path('homepage/',include ('homepage.urls')),
]

clints/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

clints/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request,'index.html')
# Create your views here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
def home(request):
    return render(request,'home.html')

def movies(request):
    return render(request,'movies.html')

def tvshows(request):
    return render(request,'Tvshows.html')
# Create your views here.

clints/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'image/netflix-logo.png' %}" type="image/x-icon">
    <title>Netflix</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body>
    <header>
        <a href="#" id="mhr"><img src="{% static 'image/netflix-logo2.png' %}" alt="" id="btn"></a>
        <div class="main-head">
            <h1>welcome to the new world</h1>
            <h2>this world of endertaiment will satisfay you</h2>
        </div>
        <div class="go-kee">
            <a href="{% url 'homepg:home' %}"><h1>Get Start</h1></a>
        </div>
    </header>
    <main>
        <div class="group-one">
            <div class="one-left">
                <div class="igs"></div>
            </div>
            <div class="one-right">
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, laudantium mollitia tempore aliquid
                    repellendus ea magni porro nulla voluptatem perspiciatis quae error, eligendi consectetur. Aut error
                    corporis nostrum dolore numquam!</h1>
            </div>
        </div>
        <div class="upcoming">
            <h1>upcoming shows</h1>
            <div class="row">
                <div class="col">
                    <img src="{% static 'images/ck.jpg' %}" alt="">
                    <h1>cobra kai season 5</h1>
                    <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Expedita assumenda non vero at, saepe sit deleniti libero fuga sequi explicabo.</h3>
                </div>
                <div class="col">
                    <img src="{% static 'images/ck.jpg' %}" alt="">
                    <h1>cobra kai season 5</h1>
                    <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Expedita assumenda non vero at, saepe sit deleniti libero fuga sequi explicabo.</h3>
                </div>
            </div>
        </div>
    </main>
    <div class="foot">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae praesentium asperiores impedit aliquid delectus amet.</p>
        <h3>copyright 2020 adventure</h3>
    </div>
</body>

</html>

homepage/templates/Tvshows.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'image/netflix-logo.png' %}" type="image/x-icon">
    <title>Netflix-tvshows</title>
    <link rel="stylesheet" href="{% static 'css/tv.css' %}">
</head>
<body>
    <header>
        <div class="tittle">
            <a href="{% url 'homepg:home' %}"><img src="{% static 'image/netflix-logo2.png' %}" alt="" id="btn"></a>
            <a href="{% url 'homepg:home' %}">Home</a>
            <a href="{% url 'homepg:shows' %}">TV Shows</a>
            <a href="{% url 'homepg:movie' %}">Movies</a>
            <a href="#">New & Nopiler</a>
            <a href="#">My List</a>
            <a href="#">Browse & Language</a>
        </div>
    </header>
    <main>
        <div class="grid-container">
            <a href=""><div class="chiled1">peaky blander</div></a>
            <a href=""><div class="chiled2">sister</div></a>
            <a href=""><div class="chiled3">dating</div></a>
            <a href=""><div class="chiled4">elite</div></a>
            <a href=""><div class="chiled5">friends</div></a>
            <a href=""><div class="chiled6">dark</div></a>
            <a href=""><div class="chiled7">100</div></a>
            <a href=""><div class="chiled8">no 1002</div></a>
          </div>
    </main>
</body>
</html>

homepage/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'image/netflix-logo.png' %}" type="image/x-icon">
    <title>Netflix-Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <header>
        <div class="tittle">
            <a href="{% url 'homepg:home' %}"><img src="{% static 'image/netflix-logo2.png' %}" alt="" id="btn"></a>
            <a href="{% url 'homepg:home' %}">Home</a>
            <a href="{% url 'homepg:shows' %}">TV Shows</a>
            <a href="{% url 'homepg:movie' %}">Movies</a>
            <a href="#">New & Nopiler</a>
            <a href="#">My List</a>
            <a href="#">Browse & Language</a>
        </div>
    </header>
    <main>
        <div class="one-gp"><h1>TV Shows</h1></div>
        <div class="container">
            <a href=""><div class="chiled1"><h3>lucifer</h3></div></a>
            <div class="chiled2"><h3></h3></div>
            <div class="chiled3"><h3>president</h3></div>
            <div class="chiled4"><h3>lucifer</h3></div>
            <div class="chiled5"><h3></h3></div>
        </div>
        <div class="one-gp"><h1>Movies</h1></div>
        <div class="container">
            <div class="chiled1"><h3>lucifer</h3></div>
            <div class="chiled2"><h3></h3></div>
            <div class="chiled3"><h3>president</h3></div>
            <div class="chiled4"><h3>lucifer</h3></div>
            <div class="chiled5"><h3></h3></div>
        </div>
        <div class="one-gp"><h1>News</h1></div>
        <div class="container">
            <div class="chiled1"><h3>lucifer</h3></div>
            <div class="chiled2"><h3></h3></div>
            <div class="chiled3"><h3>president</h3></div>
            <div class="chiled4"><h3>lucifer</h3></div>
            <div class="chiled5"><h3></h3></div>
        </div>
    </main>
</body>
</html>

homepage/templates/movies.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'image/netflix-logo.png' %}" type="image/x-icon">
    <title>Netflix-Movies</title>
    <link rel="stylesheet" href="{% static 'css/movies.css' %}">
</head>
<body>
    <header>
        <div class="tittle">
            <a href="{% url 'homepg:home' %}"><img src="{% static 'image/netflix-logo2.png' %}" alt="" id="btn"></a>
            <a href="{% url 'homepg:home' %}">Home</a>
            <a href="{% url 'homepg:shows' %}">TV Shows</a>
            <a href="{% url 'homepg:movie' %}">Movies</a>
            <a href="#">New & popiler</a>
            <a href="#">My list</a>
            <a href="#">Browes & language</a>
        </div>
    </header>
    <main>
        <div class="one-gp"><h1>movies</h1></div>
        <div class="container">
            <a href=""><div class="chiled1"><h3></h3></div></a>
            <a href=""><div class="chiled2"><h3></h3></div></a>
            <a href=""><div class="chiled3"><h3></h3></div></a>
            <a href=""><div class="chiled4"><h3></h3></div></a>
            <a href=""><div class="chiled5"><h3></h3></div></a>
            <a href=""><div class="chiled6"><h3></h3></div></a>
            <a href=""><div class="chiled7"><h3></h3></div></a>
            <a href=""><div class="chiled8"><h3></h3></div></a>
            <a href=""><div class="chiled9"><h3></h3></div></a>
            <a href=""><div class="chiled10"><h3></h3></div></a>
        </div>
    </main>